[ratios] Add prometheus counter to track cache hit rate for GetRelative (coingecko)
brave-intl/bat-go pull request #1577
Opened 2022-09-01 14:39 UTC by nvonpentz

### Summary

### Type of change ( select one )

- [ ] Product feature
- [ ] Bug fix
- [ ] Performance improvement
- [ ] Refactor
- [x] Other

### Tested Environments

- [ ] Development
- [ ] Staging
- [ ] Production

### Before submitting this PR:

- [x] Does your code build cleanly without any errors or warnings?
- [x] Have you used auto closing keywords?
- [ ] Have you added tests for new functionality?
- [ ] Have validated query efficiency for new database queries?
- [ ] Have documented new functionality in README or in comments?
- [ ] Have you squashed all intermediate commits?
- [ ] Is there a clear title that explains what the PR does?
- [ ] Have you used intuitive function, variable and other naming?
- [ ] Have you requested security / privacy review if needed
- [ ] Have you performed a self review of this PR?

### Manual Test Plan:

2022-09-01 14:57 UTC, husobee requested changes

2022-09-02 12:07 UTC, husobee commented on services/ratios/service.go
> +			"query":  "coinIDs=" + coinIDs.String() + "&vsCurrencies=" + vsCurrencies.String(),
deferred to a later date.

2022-09-02 12:07 UTC, husobee approved these changes
lgtm

2022-09-02 12:40 UTC, nvonpentz commented
Merging now to get this out there, but will most likely follow up with  more changes and improvements as I learn more

2022-09-02 12:41 UTC, merged