Add date header to enclave response
brave-intl/bat-go pull request #2187
Opened 2023-10-31 20:08 UTC by Sneagan

### Summary

closes #2150

### Type of Change

- [ ] Product feature
- [ ] Bug fix
- [ ] Performance improvement
- [ ] Refactor
- [ ] Other

### Tested Environments

- [ ] Development
- [ ] Staging
- [ ] Production

### Before Requesting Review

- [ ] Does your code build cleanly without any errors or warnings?
- [ ] Have you used auto closing keywords?
- [ ] Have you added tests for new functionality?
- [ ] Have validated query efficiency for new database queries?
- [ ] Have documented new functionality in README or in comments?
- [ ] Have you squashed all intermediate commits?
- [ ] Is there a clear title that explains what the PR does?
- [ ] Have you used intuitive function, variable and other naming?
- [ ] Have you requested security and/or privacy review if needed
- [ ] Have you performed a self review of this PR?

2023-10-31 23:09 UTC, evq commented on libs/httpsignature/httpsignature_test.go
> +		fmt.Println(s.Sig)
can we remove this?

2023-10-31 23:19 UTC, evq approved these changes
lgtm other than that one nit

2023-11-01 14:32 UTC, husobee requested changes
will push a few small changes which will remove this extra middleware requirement

2023-11-01 14:42 UTC, husobee approved these changes

2023-11-01 15:57 UTC, merged